### ISSUE TITLE
Version number downgraded to v0.1

### ISSUE THREAD

**Issue by EdoAlvarezR** [byuflowlab/BPM.jl#3]
Version number got accidentally downgraded from v2.0.1 to v0.1 in this commit: [LINK](https://github.com/byuflowlab/BPM.jl/commit/893bc4cd4971e107c8b8bd0bad685be162e4ed5f). 

Suggested correction: stage master version to v2.0.2 (assuming no breaking changes were introduced).

([I released v2.0.1](https://github.com/byuflowlab/BPM.jl/releases/tag/v2.0.1) a few minutes ago from an old commit in order to avoid breaking other packages that depend on BPM.jl)

**Comment by taylormcd** [comment]
There were definitely breaking changes.  I changed it up to v3.0.
